services:
  authenticator:
    build: .
    container_name: authenticator
    ports:
      - "8001:8000"
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'root'
      MYSQL_PSWD: 'password123'
      MYSQL_PORT: 3306
      DATABASE_NAME: 'bankmatrix'
      SERVICE: 'authenticator'
    image: 127.0.0.1:5000/virtual-banking-system-prototype-authenticator:latest

  user_account:
    build: .
    container_name: user_account
    ports:
      - "8002:8000"
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'root'
      MYSQL_PSWD: 'password123'
      MYSQL_PORT: 3306
      DATABASE_NAME: 'bankmatrix'
      SERVICE: 'userAccount'
    image: 127.0.0.1:5000/virtual-banking-system-prototype-user-account:latest

  transfer:
    build: .
    container_name: transfer
    ports:
      - "8003:8000"
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'root'
      MYSQL_PSWD: 'password123'
      MYSQL_PORT: 3306
      DATABASE_NAME: 'bankmatrix'
      SERVICE: 'transfer'
    image: 127.0.0.1:5000/virtual-banking-system-prototype-transfer:latest

  transaction:
    build: .
    container_name: transaction
    ports:
      - "8004:8000"
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'root'
      MYSQL_PSWD: 'password123'
      MYSQL_PORT: 3306
      DATABASE_NAME: 'bankmatrix'
      SERVICE: 'transaction'
    image: 127.0.0.1:5000/virtual-banking-system-prototype-transaction:latest

  db:
    image: mysql:8.0
    container_name: bankmatrixdb
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'password123'
      MYSQL_DATABASE: 'bankmatrix'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
